/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jaen;
import java.awt.Font;
import java.lang.Thread.State;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class Stock extends javax.swing.JFrame {

    
    public Stock() {
        initComponents();
        table_update();
        Header();
        date();
        PanelAdd.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     Connection con1;
     PreparedStatement insert;
     PreparedStatement insert2;
     ResultSet rs;
     ResultSet rs2;
     Statement state;

     
     public void Header(){
         
         jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD, 30));
     }
    
    private void table_update(){
           
           int c;
           
             try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            insert = con1.prepareStatement("select * from stock");
            
            rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("Stock_ID"));
                    v2.add(rs.getString("Type_of_Stock"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("Quantity"));
                    v2.add(rs.getString("Type_of_the_Stock"));
                    v2.add(rs.getString("Date_Recieve"));
       
                }
                
                Df.addRow(v2);
                        
            }
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
       }

    public void date(){
        Date date = new Date();
       SimpleDateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
        String currentdate = dateformat.format(date);
        lblDate.setText(currentdate);
    }
  
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelAdd1 = new javax.swing.JPanel();
        PanelAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStocktype = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtQuan1 = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtSupplyID = new javax.swing.JTextField();
        txtDelivery = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblFertilizer = new javax.swing.JLabel();
        ComboStock = new javax.swing.JComboBox<>();
        lblName1 = new javax.swing.JLabel();
        lblStockID = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jComboName = new javax.swing.JComboBox<>();
        txtType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Supply Stock's");

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyImages/back3.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 110));

        PanelAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        PanelAdd1.setOpaque(false);
        PanelAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAdd.setBackground(new java.awt.Color(102, 255, 0));
        PanelAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        PanelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("Search Supply");
        PanelAdd.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Stock Type");
        PanelAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 153, 40));

        txtStocktype.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PanelAdd.add(txtStocktype, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Name");
        PanelAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 153, 42));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Qauntity");
        PanelAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 153, 40));

        txtQuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PanelAdd.add(txtQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText("Description");
        PanelAdd.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 153, 40));

        txtDesc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PanelAdd.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 220, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Delivery Name");
        PanelAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Add Stock");
        PanelAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 37));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("Add Quantity");
        PanelAdd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 153, 40));

        txtQuan1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtQuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuan1ActionPerformed(evt);
            }
        });
        PanelAdd.add(txtQuan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 220, -1));

        btnAdd1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        PanelAdd.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 105, -1));

        btnCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        PanelAdd.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 40));

        txtName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        PanelAdd.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 42));

        txtSupplyID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtSupplyID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplyIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplyIDKeyReleased(evt);
            }
        });
        PanelAdd.add(txtSupplyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, -1));

        txtDelivery.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryActionPerformed(evt);
            }
        });
        PanelAdd.add(txtDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 220, -1));

        lblDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PanelAdd.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 40));

        PanelAdd1.add(PanelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 460, 470));

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuantity.setText("Quantity");
        PanelAdd1.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 150, 50));

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblType.setText("Stock Type");
        PanelAdd1.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 50));

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        PanelAdd1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 260, 50));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        PanelAdd1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 140, 50));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        PanelAdd1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 130, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        PanelAdd1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 120, 50));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        PanelAdd1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 50));

        lblFertilizer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFertilizer.setText("Delivery Name");
        PanelAdd1.add(lblFertilizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 210, 50));

        ComboStock.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ComboStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seeds", "Fertilizer" }));
        ComboStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStockActionPerformed(evt);
            }
        });
        PanelAdd1.add(ComboStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 260, 50));

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblName1.setText("Name");
        PanelAdd1.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 150, 50));

        lblStockID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStockID.setText("Stock ID");
        PanelAdd1.add(lblStockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 50));

        txtStockID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtStockID.setOpaque(true);
        PanelAdd1.add(txtStockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 260, 50));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        PanelAdd1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 40, 140, 40));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSearch.setText("Search Stock");
        PanelAdd1.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 40, -1, 40));

        jComboName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jComboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNameActionPerformed(evt);
            }
        });
        PanelAdd1.add(jComboName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 260, 50));

        txtType.setEditable(false);
        txtType.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PanelAdd1.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 260, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelAdd1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 100, 50));

        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Stock ID", "Type od Stock", "Stock Name", "Quantity", "Description", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 204, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(51, 204, 0));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        PanelAdd1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1580, 200));
        PanelAdd1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1428, 340, 160, 40));

        jPanel1.add(PanelAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 1640, 820));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(1909, 1081));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    
    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // This is for the update button 
       DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
            try {

        String stockid = txtStockID.getText();
        String type = ComboStock.getSelectedItem().toString();
        String name = jComboName.getSelectedItem().toString();
        String qty = txtQuantity.getText();
        String types = txtType.getText();
      
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            insert = con1.prepareStatement("update stock set Type_of_Stock=?, Name=?, Quantity=?, Type_of_the_Stock=? where Stock_ID=?");
            
            insert.setString(5, stockid);
            insert.setString(1, type);
            insert.setString(2, name);
            insert.setString(3, qty);
            insert.setString(4, types);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Update!!");
            table_update();
            
      
          txtQuantity.setText("");
       
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat format =  new SimpleDateFormat("yyyy-MM-dd");
         
        String stockid = txtStockID.getText();
        String type = ComboStock.getSelectedItem().toString();
        String name = jComboName.getSelectedItem().toString();
        String qty = txtQuantity.getText();
        String types = txtType.getText();
        String date = format.format(jDateChooser1.getDate());
       
 
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            insert = con1.prepareStatement("insert into stock(Stock_ID,Type_of_Stock,Name,Quantity,Type_of_the_Stock,"
                    + "Date_Recieve)values(?,?,?,?,?,?)");
           
            insert.setString(1, stockid);
            insert.setString(2, type);
            insert.setString(3, name);
            insert.setString(4, qty);
            insert.setString(5, types);  
            insert.setString(6, date);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Addedd!!");
            table_update();         
          
          txtQuantity.setText("");
                   
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     int op =JOptionPane.showConfirmDialog(null, "Are you sure to Delete", "Delete", JOptionPane.YES_NO_OPTION);
        if(op == 0){
        try {
          
            Class.forName("com.mysql.cj.jdbc.Driver");
             con1= DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
             
              int row = jTable1.getSelectedRow();
              String value = (jTable1.getModel().getValueAt(row, 0).toString());
              String query = "DELETE FROM stock where Stock_ID=?";
              insert = con1.prepareStatement(query);
              insert.setString(1,txtStockID.getText());
               insert.executeUpdate();
               
                JOptionPane.showMessageDialog(null, "Delete Success");
              table_update();
        
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
             
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
       
          txtQuantity.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        
        try{
            String query =" SELECT * FROM stock WHERE Stock_ID = ?";
            insert=con1.prepareStatement(query);
            insert.setString(1, txtSearch.getText());
            rs = insert.executeQuery();
            
             DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
             String search = txtSearch.getText();
             TableRowSorter< DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(Df);
             jTable1.setRowSorter(trs);
             trs.setRowFilter(RowFilter.regexFilter(search));
  
        }catch (Exception e){
            
        }
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void ComboStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStockActionPerformed
        // TODO add your handling code here:
          try{
            
                Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            String query ="SELECT Type_of_Stock,Stock_Variety from agri_supply where Type_of_Stock = ?";
            insert=con1.prepareStatement(query);
            insert.setString(1, ComboStock.getSelectedItem().toString());
            rs = insert.executeQuery();
            
            if(ComboStock.getSelectedItem().equals("Seeds"))
            {
               jComboName.removeAllItems();
                while(rs.next()){
                      
                      String stock = rs.getString("Stock_Variety");
                      
                      jComboName.addItem(stock);
                      
                }
            }
              if(ComboStock.getSelectedItem().equals("Fertilizer"))
            {
               jComboName.removeAllItems();
                while(rs.next()){
                    
                      String stock = rs.getString("Stock_Variety");
                      jComboName.addItem(stock);
                }
            }
            
             
            
   
            
        }catch(Exception e){
            
        }
          
      
     
        
    }//GEN-LAST:event_ComboStockActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        AgriSupply sup = new AgriSupply();
        sup.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jComboNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNameActionPerformed
        // TODO add your handling code here:
      
            try{
            
                Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            String query ="SELECT Stock_Variety,Stock_Description from agri_supply where Stock_Variety = ?";
            insert2=con1.prepareStatement(query);
            insert2.setString(1, jComboName.getSelectedItem().toString());
            rs2 = insert2.executeQuery();
        
               if(jComboName.getSelectedItem().equals("RC-222"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
               
               if(jComboName.getSelectedItem().equals("RC-132H"))
            {
              txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
               
                 if(jComboName.getSelectedItem().equals("RC-140H"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
                   if(jComboName.getSelectedItem().equals("RC-236H"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
                     if(jComboName.getSelectedItem().equals("RC-456H"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
                       if(jComboName.getSelectedItem().equals("RC-534"))
            {
              txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
                         if(jComboName.getSelectedItem().equals("RC-436"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                      
                }
            }
                           if(jComboName.getSelectedItem().equals("RC-480"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                      
                      String stock = rs2.getString("Stock_Description"); 
                      txtType.setText(stock);
                      
                }
            }
               
               
               
              if(jComboName.getSelectedItem().equals("Urea"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                    
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                }
            }
              
              if(jComboName.getSelectedItem().equals("Abono"))
            {
               txtType.setText(" ");
                while(rs2.next()){
                    
                      String stock = rs2.getString("Stock_Description");
                      txtType.setText(stock);
                }
            }
           
            
        }catch(Exception e){
            
        }
        
        
      
    }//GEN-LAST:event_jComboNameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelAdd.show();
        txtSearch.setEnabled(false);
        jTable1.setEnabled(false);
        txtStockID.setEnabled(false);
        ComboStock.setEnabled(false);
        jComboName.setEnabled(false);
        txtQuantity.setEnabled(false);
        jDateChooser1.setEnabled(false);
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        jButton1.setEnabled(false);
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSupplyIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplyIDKeyReleased
        // TODO add your handling code here:
         try{
            String query =" SELECT * FROM stock WHERE Stock_ID = ?";
            insert=con1.prepareStatement(query);
            insert.setString(1, txtSupplyID.getText());
            rs = insert.executeQuery();
            
  
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_txtSupplyIDKeyReleased

    private void txtSupplyIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplyIDKeyPressed
        // TODO add your handling code here:
         String search = txtSupplyID.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");
            insert = con1.prepareStatement("select * from stock where Stock_ID = ?");
            insert.setString(1,search);
            rs = insert.executeQuery();

            if (rs.next() == false)
            {
                
            }
            else
            {
               
                String Username = rs.getString("Type_of_Stock");
                String Password = rs.getString("Name");
                String Name = rs.getString("Quantity");
                String Address = rs.getString("Type_of_the_Stock");
                String Email = rs.getString("Date_Recieve");
                
             
                txtStocktype.setText(Username.trim());
                txtName.setText(Password.trim());
                txtQuan.setText(Name.trim());
                txtDesc.setText(Address.trim());
              
                
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSupplyIDKeyPressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        PanelAdd.hide();       
        txtSearch.setEnabled(true);
        jTable1.setEnabled(true);
        txtStockID.setEnabled(true);
        ComboStock.setEnabled(true);
        jComboName.setEnabled(true);
        txtQuantity.setEnabled(true);
        jDateChooser1.setEnabled(true);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        jButton1.setEnabled(true);
       
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryActionPerformed

    private void txtQuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuan1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
         try {
             
            
             
        Date date = new Date();
        SimpleDateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
        String currentdate = dateformat.format(date);
        lblDate.setText(currentdate);
        
        String supplyID  = txtSupplyID.getText();
        String stockType = txtStocktype.getText();
        String stockName = txtName.getText();        
        String desc = txtDesc.getText();
        String adqty = txtQuan1.getText();        
        String delivery = txtDelivery.getText();
        String quan = txtQuan.getText();
        

       if (supplyID.isEmpty() || stockType.isEmpty() || stockName.isEmpty() || desc.isEmpty() || adqty.isEmpty() || delivery.isEmpty()
                      || quan.isEmpty()){     
                    JOptionPane.showMessageDialog(null, "Fill the Blank!","Complete the details", JOptionPane.ERROR_MESSAGE);
                
                }else{
           
        int quantity = Integer.parseInt(quan);
        int add = Integer.parseInt(adqty);
        int Total = quantity + add;
        String total = Integer.toString(Total);
             
               Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/registar","root","DANIEL05");      
            insert= con1.prepareStatement("update stock set Quantity=? where Stock_ID =?");
                       
            insert.setString(1, total);
            insert.setString(2,supplyID);
            insert.executeUpdate();

            insert = con1.prepareStatement("insert into stock_delivered(Date_Delivered,Stock_ID,Type_of_Stock,Name,Quantity_Delivered,Type_of_the_Stock,Name_of_Delivery_Man   )values(?,?,?,?,?,?,?)");
                 
            insert.setString(1, currentdate); 
            insert.setString(2, supplyID);
            insert.setString(3, stockType);
            insert.setString(4, stockName);
            insert.setString(5, adqty);
            insert.setString(6, desc);
            insert.setString(7, delivery);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Addedd!!");
                        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStock;
    private javax.swing.JPanel PanelAdd;
    private javax.swing.JPanel PanelAdd1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFertilizer;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStockID;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtDelivery;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuan;
    private javax.swing.JTextField txtQuan1;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStockID;
    private javax.swing.JTextField txtStocktype;
    private javax.swing.JTextField txtSupplyID;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
